import bootstrap from 'bootstrap/dist/css/bootstrap.css';


import './globals.css'
import Navbar from './components/navbar/pages';
import Footer from './components/footer/page'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navbar />
      {children}
      <Footer />
      </body>
    </html>
  )
}
